apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    type: web
spec:
  selector:
    task: task3
  type: NodePort
  ports:
    - nodePort: 31111
      port: 81
      targetPort: 80
